name: condaenv_cloud
channels:
  - fastai
  - nvidia
  - conda-forge
  - conda-forge/label/broken  # required imagecodecs is marked broken
dependencies:
  - albumentations=1.0.3
  - catboost=0.26.1
  - cudatoolkit=11.1.74=h6bb024c_0
  - cudnn=8.2.1.32=h86fa8c9_0
  - fastai=2.5.0
  - geos=3.9.1
  - geotiff=1.6.0
  - h5py=3.1.0
  - imageio=2.9.0
  - keras=2.6.0
  - loguru=0.5.3
  - mkl=2020.4
  - numpy=1.20.3
  - numba=0.54.1
  - pandas=1.2.5
  - pillow=8.2.0
  - pip=20.3.4
  - pydantic=1.8.2
  - pydap=3.2.2
  - pyepsg=0.4.0
  - pygeos=0.10.1
  - pyproj=3.3.0
  - pystac-client=0.3.1
  - pytest=6.2.4
  - python=3.9.7
  - pytorch-lightning=1.4.1
  - pytorch=1.8.0=cuda111py39h37e5b68_1
  - rasterio=1.2.6
  - scikit-image=0.18.2
  - scikit-learn=0.24.2
  - scipy=1.7.1
  - segmentation-models-pytorch=0.2.1
  - shapely=1.7.1
  - stackstac=0.2.2
  - tifffile=2021.8.8
  - tiledb=2.3.2
  - timm=0.4.12
  - torchvision=0.9.1=py39cuda111hcd06603_1_cuda
  - tqdm=4.62.0
  - typer=0.3.2
  - xarray=0.19.0
  - pip:
    - cloudpathlib[azure]==0.6.2
    - crfseg==1.0.0
    - lightning-flash[image]==0.5.0
    - mmcv-full==1.3.9
    - mmsegmentation==0.16.0
    - nnunet==1.7.0
    - pandas_path==0.3.0
    - planetary-computer==0.4.2
    - rioxarray==0.9.0
    - segmentation-models==1.0.1
    - tensorflow-gpu==2.6.0
    - ttach==0.0.3
    - xarray-spatial==0.3.0